media:
  input: public
  output: /

content:
  - name: products
    label: Productos
    type: collection
    path: src/content/products
    view:
      fields: [ name, price, category, available ]
    fields:
      - { name: name, label: Nombre del producto, type: string, required: true }
      - { name: price, label: Precio, type: number, required: true }
      - { name: description, label: Descripción, type: string }
      - { name: ingredients, label: Ingredientes, type: string, list: true }
      - { name: category, label: Categoría, type: string }
      - { name: available, label: Disponible, type: boolean, default: true }
      - { name: image, label: Imagen, type: string, options: { input: public/images/products, output: /images/products } }
      - { name: body, label: Body, type: rich-text }
