media:
  input: public
  output: /images

content:
  - name: products
    label: Productos
    type: collection
    path: src/content/products
    view:
      fields: [name, price, category, available]
    fields:
      - name: name
        label: Nombre del producto
        type: string
        required: true

      - name: slug
        label: Slug
        type: string

      - name: category
        label: Categoría
        type: string

      - name: description
        label: Descripción
        type: string

      - name: ingredients
        label: Ingredientes
        type: string
        list: true

      - name: price
        label: Precio
        type: number
        required: true

      - name: image
        label: Imagen
        type: image

      - name: available
        label: Disponible
        type: boolean
        default: true

      - name: body
        label: Información adicional
        type: rich-text


  - name: drinks
    label: Bebidas
    type: collection
    path: src/content/drinks
    view:
      fields: [name, price, available]
    fields:
      - name: name
        label: Nombre de la bebida
        type: string
        required: true

      - name: slug
        label: Slug
        type: string

      - name: description
        label: Descripción
        type: string

      - name: price
        label: Precio
        type: number
        required: true

      - name: image
        label: Imagen
        type: image

      - name: available
        label: Disponible
        type: boolean
        default: true

      - name: body
        label: Información adicional
        type: rich-text


  - name: categories
    label: Categorías de menú
    type: collection
    path: src/content/categories
    view:
      fields: [name]
    fields:
      - name: name
        label: Nombre de la categoría
        type: string
        required: true

      - name: slug
        label: Slug
        type: string

      - name: description
        label: Descripción
        type: string
